
# <h3 align="center"> **Aula Prática**</h3> 




<h3 align="center"> Data: 26/04/2021</h3> 

Vamos iniciar estudando o comportamento de SVM com diferentes tipos de kernel.


In [1]:
# Importando bibliotecas necessárias
import numpy as np
import sklearn

Descrição da base de dados

Nesse exemplo, nós utilizaremos a base **Breast Cancer**, a qual está disponível no sklearn mas é originária do repositório da UCI (https://archive.ics.uci.edu/ml/datasets/breast+cancer). Trata-se de uma base de dados que foi obtida a partir de imagens digitalizadas de massas mamárias e que descrevem **dois** tipos de classe: maligno (*harmful*) e benigno (not harmful). Os atributos descrevem características dos núcleos celulares presentes nas imagens.

No total, são **30 atributos** ordenados: raio médio, textura média, perímetro médio, área média, suavidade média, compacidade média, concavidade média, pontos côncavos médios, simetria média, dimensão fractal média, erro de raio, erro de textura, erro de perímetro, erro de área, erro de suavidade, erro de compactação, erro de concavidade, erro de pontos côncavos, erro de simetria, erro de dimensão fractal, pior raio, pior textura, pior perímetro, pior área, pior suavidade, pior compacidade, pior concavidade, piores pontos côncavos, pior simetria e pior dimensão fractal) e um alvo (tipo de câncer).

Nós vamos utilizar o Pandas para facilitar a visualização dos dados estruturados

In [2]:
#Importando as bibliotecas
import pandas as pd
from sklearn import datasets

#Carregando a base de dados
cancer = datasets.load_breast_cancer()

In [4]:
#Vamos visualizar os dados

cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
#Convertendo o dataset do Sklearn para o Dataframe do Pandas. Para isso,  nós vamos concatenar target e data usando o numpy 

df = pd.DataFrame(np.c_[cancer['data'], cancer['target']], columns = np.append(cancer['feature_names'], ['target']))

#Para visualizar os dados na forma de tabela
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 31 columns]

In [17]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890     0.0  
1                  0.1860          0.2750                  0.08902     0.0  
2                  0.2430          0.3613                  0.08758     0.0  
3                  0.2575          0.6638                  0.17300     0.0  
4                  0.1625          0.2364                  0.076

Como nós faremos ajustes dos parâmetros dos métodos de geração de conjuntos, nós vamos dividir a base em três partições: treino, validação e teste. A base de treino terá 60% das instâncias, enquanto as bases de teste e de validação terão 20% cada.

In [7]:
#Vamos, inicialmente, dividir a base em duas partições: treino e teste. A base de treino terá 80% das instâncias (essa versão da base será utilizada no final para a comparação final dos modelos), enquanto a de teste terá 20%

from sklearn.model_selection import train_test_split

#Dividindo a base (com seleção de instâncias aleatória)
X_train80, X_test, y_train80, y_test = train_test_split(cancer.data, cancer.target, test_size=0.2, random_state = 42)
#*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None
#Checando a divisão das instâncias entre as duas bases 
print(X_train80.shape, y_train80.shape)
print(X_test.shape, y_test.shape)

(455, 30) (455,)
(114, 30) (114,)


Agora vamos dividir a base de treino em duas bases: treino e validação. Ao final, a base de treino terá 60% das instâncias originais, enquanto a base de validação terá 20%, assim como a base de teste já criada.

In [8]:
#Dividindo a base de treino (com seleção de instâncias aleatória)
X_train, X_val, y_train, y_val = train_test_split(X_train80, y_train80, test_size=0.25, random_state = 42)

#Checando a divisão das instâncias entre as duas bases
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

(341, 30) (341,)
(114, 30) (114,)


In [9]:
#Como os atributos originais estão em diferentes escalas, nós vamos normalizar os dados aqui

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_val = sc.transform(X_val)


In [10]:
#Normalização dos dados para versão com apenas partições de treino e de teste

X_train80 = sc.fit_transform(X_train80)  
X_test = sc.transform(X_test)

###**Experimentos com SVM**
Nós utilizaremos inicialmente SVM parar classificar os dados da base.
Embora nós não tenhamos muitas explicações sobre a distribuição dos dados, nós vamos utilizar SVM não linear. Aqui, nós vamos criar dois modelos de SVM: **1)** um modelo não linear com kernel polinomial; e **2)** um modelo não linear com kernel RBF. Vamos iniciar com o **kernel polinomial**.

In [11]:
from sklearn import svm

#Importando o módulo de cálculo de métricas de avaliação do scikit-learn 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [14]:
# Definição do algoritmo e passagem de parâmetros. O kernel polinomial, além do grau, tem como parâmetro gamma. Neste caso, nós deixaremos gamma como o valor default.

modelo_polinomial = svm.SVC(kernel='poly', degree=3, C=10) # Kernel Polinomial com parâmetro de regularização C = 10

#Vamos treinar o modelo usando a base X_Train

modelo_polinomial.fit(X_train, y_train)


SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
#Vamos fazer as predições para a base de validação

train_pred_Modelo_poli = modelo_polinomial.predict(X_train)
y_pred_poli = modelo_polinomial.predict(X_val)

In [16]:
# Comparando acurácia no treino e em validação
print("Acurácia no treino", accuracy_score(y_train, train_pred_Modelo_poli))
print("Acurácia na validação", accuracy_score(y_val, y_pred_poli))

Acurácia no treino 0.9765395894428153
Acurácia na validação 0.956140350877193


## **Avaliação do modelo**

In [19]:
# Avaliação do modelo

print(confusion_matrix(y_val,y_pred_poli))
print(classification_report(y_val,y_pred_poli))  
print("Acurácia Polinomial:", accuracy_score(y_val, y_pred_poli))

[[39  5]
 [ 0 70]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94        44
           1       0.93      1.00      0.97        70

    accuracy                           0.96       114
   macro avg       0.97      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114

Acurácia Polinomial: 0.956140350877193


In [20]:
#Gerando o modelo com kernel RBF

modelo_rbf = svm.SVC(kernel='rbf', gamma=0.1, C=10) # Kernel RBF com parâmetro de regularização C = 10
#Vamos treinar o modelo usando a base X_Train

modelo_rbf.fit(X_train, y_train)


SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [21]:
#Vamos fazer as predições para a base de validação

train_pred_modelo_rbf = modelo_rbf.predict(X_train)
y_pred_rbf = modelo_rbf.predict(X_val)

In [22]:
# Comparando acurácia no treino e em validação
print("Acurácia no treino", accuracy_score(y_train, train_pred_modelo_rbf))
print("Acurácia na validação", accuracy_score(y_val, y_pred_rbf))

Acurácia no treino 1.0
Acurácia na validação 0.9473684210526315


In [24]:
# Avaliação do modelo

print(confusion_matrix(y_val,y_pred_rbf))
print(classification_report(y_val,y_pred_rbf))  
print("Acurácia RBF:", accuracy_score(y_val, y_pred_rbf))

[[42  2]
 [ 4 66]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93        44
           1       0.97      0.94      0.96        70

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.94       114
weighted avg       0.95      0.95      0.95       114

Acurácia RBF: 0.9473684210526315


### **Ajuste de Hiperparâmetros**
Ajustar os hiperparâmetros manualmente até que se encontre uma ótima combinação de valores seria uma tarefa bastante difícil. Para evitar ter que fazer essa busca de forma manual, nós utilizaremos o **GridSearchCV** do Scikit-Learn para pesquisar os valores. É suficiente informar quais hiperparâmetros deseja-se experimentar e quais valores devem ser testados. O **GridSearchCV** avaliará todas as combinações possíveis de valores de hiperparâmetros usando validação cruzada.

In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

modelo_rbf = svm.SVC 
svm_clf = GridSearchCV(modelo_rbf(kernel='rbf'), param_grid, cv=5)
svm_clf.fit(X_train, y_train)


GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [29]:
svm_clf.best_estimator_

SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [31]:
# Verificando acurácia na validação
y_pred = svm_clf.predict(X_val)
print("Acurácia na validação", accuracy_score(y_val, y_pred))

Acurácia na validação 0.9649122807017544


In [33]:
# Avaliação do modelo

print(confusion_matrix(y_val,y_pred))
print(classification_report(y_val,y_pred))  
print("Acurácia RBF Otimizado:", accuracy_score(y_val, y_pred))

[[42  2]
 [ 2 68]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95        44
           1       0.97      0.97      0.97        70

    accuracy                           0.96       114
   macro avg       0.96      0.96      0.96       114
weighted avg       0.96      0.96      0.96       114

Acurácia RBF Otimizado: 0.9649122807017544


In [34]:
#Fixando a melhor configuração definida por GridSearch com kernel RBF

svm_clf = svm.SVC(kernel='rbf', gamma=0.0001, C=1000) 

### **Mudando de classificador**
Aqui nós vamos utilizar Árvores de Decisão. O **GridSearchCV** será também aplicado para encontrar os melhores valores de hyperparâmetros para a Árvore de Decisão. **Obeservação**: Serão testados diferentes valores para *max_leaf_nodes* e para *min_samples_split*.

In [35]:
from sklearn.tree import DecisionTreeClassifier



In [36]:
params = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [2, 3, 4]}
dt_clf = GridSearchCV(DecisionTreeClassifier(random_state=42), params, verbose=1, cv=5)

dt_clf.fit(X_train, y_train)



Fitting 5 folds for each of 294 candidates, totalling 1470 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1470 out of 1470 | elapsed:    4.6s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=42,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'max_leaf_nodes': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,


In [37]:
dt_clf.best_estimator_

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [39]:
# Avaliação da Árvore de Decisão da base de validação

#Antes de avaliar, nós faremos um novo treino considerando a melhor configuração definida via GridSearch
dt_clf = DecisionTreeClassifier(random_state=42, max_leaf_nodes=5, min_samples_split=2) 
dt_clf.fit(X_train, y_train)

# Testando
train_pred_dt_clf = dt_clf.predict(X_train)
y_pred_dt_clf = dt_clf.predict(X_val)

# Comparando acurácia no treino e em validação
print("Acurácia no treino", accuracy_score(y_train, train_pred_dt_clf))
print("Acurácia na validação", accuracy_score(y_val, y_pred_dt_clf))


Acurácia no treino 0.9736070381231672
Acurácia na validação 0.9298245614035088


### **Utilizando Comitê de Preditores**
Será que um comitê é melhor do que um preditor individual?
Aqui, nós vamos verificar o desempenho de **Boosting** (GradientBoosting) e **Random Fores**t, todos utilizados com o Árvore de Decisão como algoritmo de base. Nós vamos comparar o resultado obtido por cada método de geração de conjunto com o resultado acima, obtido por uma árvore de decisão, e com o resultado obtido por SVM.

In [40]:
# Chamando os métodos que serão utilizados
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [41]:
#Random Forest : gerando o modelo

rf_clf = RandomForestClassifier(n_estimators=15, random_state=42)

# Treinando e testando 
rf_clf.fit(X_train, y_train)

train_pred_modelo_rf = rf_clf.predict(X_train)
y_pred_rf = rf_clf.predict(X_val)

# Comparando acurácia no treino e em validação
print("Acurácia no treino", accuracy_score(y_train, train_pred_modelo_rf))
print("Acurácia na validação", accuracy_score(y_val, y_pred_rf))


Acurácia no treino 0.9970674486803519
Acurácia na validação 0.9473684210526315


In [42]:
#GradientBoosting
gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, random_state=42)

# Treinando, testando e avaliando
gb_clf.fit(X_train, y_train)

train_pred_modelo_gb = gb_clf.predict(X_train)
y_pred_gb = gb_clf.predict(X_val)

# Comparando acurácia no treino e em validação
print("Acurácia no treino", accuracy_score(y_train, train_pred_modelo_gb))
print("Acurácia na validação", accuracy_score(y_val, y_pred_gb))

Acurácia no treino 1.0
Acurácia na validação 0.9736842105263158


In [43]:
# Avaliação do modelo

print(confusion_matrix(y_val,y_pred_gb))
print(classification_report(y_val,y_pred_gb))  
print("Acurácia de Gradient Boosting:", accuracy_score(y_val, y_pred_gb))

[[42  2]
 [ 1 69]]
              precision    recall  f1-score   support

           0       0.98      0.95      0.97        44
           1       0.97      0.99      0.98        70

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Acurácia de Gradient Boosting: 0.9736842105263158


### **Comparação entre os diversos modelos**
Aqui, nós utilizaremos a versão completa da base de treinamento, ou seja, 80% das instâncias da base original

In [44]:
for clf in (svm_clf, dt_clf, rf_clf, gb_clf):
    clf.fit(X_train80, y_train80)
    name = clf
    y_pred_name = clf.predict(X_test)
    print("Acurácia", clf.__class__.__name__,  accuracy_score(y_test, y_pred_name))
    print(classification_report(y_test,y_pred_name))
    
   

Acurácia SVC 0.9736842105263158
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Acurácia DecisionTreeClassifier 0.9473684210526315
              precision    recall  f1-score   support

           0       0.95      0.91      0.93        43
           1       0.95      0.97      0.96        71

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

Acurácia RandomForestClassifier 0.9649122807017544
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96     