In [1]:
import pandas as pd
import sklearn
import numpy as np
import csv
from csv import reader
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("train_data3.csv")
df.head()

paciente  Jitter_local  Jitter_local_absolute  Jitter_rap  Jitter_ppq5  \
0        40         471.0               0.000034       186.0         0.23   
1        40        4319.0               0.000317      2774.0      1708.00   
2        40        1543.0               0.000103      1004.0       648.00   
3        40        2864.0               0.000212      1108.0      1147.00   
4        40        3878.0               0.000301      1795.0      1675.00   

   Jitter_ddp  Shimmer_local  Shimmer_localdB  Shimmer_apq3  Shimmer_apq5  \
0       558.0         2793.0             0.26        1183.0          1.52   
1      8322.0        13924.0          1195.00        8558.0       6036.00   
2      3012.0        17447.0          1694.00       11171.0       6851.00   
3      3324.0         7692.0          1062.00        2555.0       4647.00   
4      5386.0        11574.0          1212.00        3994.0          5.69   

   ...  Num_pulses  Num_periods  Mean_periods  Standard_deviation_period   \
0  ...         176          175      0.007179                    0.000130   
1  ...         258          256      0.007343                    0.000312   
2  ...         426          425      0.006700                    0.000108   
3  ...          74           70      0.007405                    0.000660   
4  ...          71           68      0.007766                    0.001045   

   Fraction_locally_unvoiced_frames  Num_voice_breaks  Degree_voice_breaks  \
0                               0.0                 0                 0.00   
1                            2913.0                 1              7038.00   
2                             351.0                 0                 0.00   
3                           18056.0                 2              6777.00   
4                           25333.0                 2                11.75   

   UPDRS  Exame  Sick  
0      1      1     0  
1      1      2     0  
2      1      3     0  
3      1      4     0  
4      1      5     0  

[5 rows x 30 columns]

In [3]:
df.Sick

0       0
1       0
2       0
3       0
4       0
       ..
1035    1
1036    1
1037    1
1038    1
1039    1
Name: Sick, Length: 1040, dtype: int64

In [4]:
##testando se o csv ficou arrumado##

In [5]:
df.shape

(1040, 30)

In [6]:
##Checando se tem duplicados

In [7]:
sum(df.duplicated())

0

In [8]:
df.shape

(1040, 30)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   paciente                          1040 non-null   int64  
 1   Jitter_local                      1040 non-null   float64
 2   Jitter_local_absolute             1040 non-null   float64
 3   Jitter_rap                        1040 non-null   float64
 4   Jitter_ppq5                       1040 non-null   float64
 5   Jitter_ddp                        1040 non-null   float64
 6   Shimmer_local                     1040 non-null   float64
 7   Shimmer_localdB                   1040 non-null   float64
 8   Shimmer_apq3                      1040 non-null   float64
 9   Shimmer_apq5                      1040 non-null   float64
 10  Shimmer_apq11                     1040 non-null   float64
 11  Shimmer_dda                       1040 non-null   float64
 12  AC    

In [10]:
#apaga a coluna de pacientes ID
del df['paciente']
del df['UPDRS']
df.shape

(1040, 28)

In [11]:
#####################################################
#preparando os dados
#####################################################

In [12]:
from sklearn.model_selection import train_test_split

def embaralha(x,y):
    X_aux, X_emb, y_aux, y_emb = train_test_split(x, y, test_size=0.95 ,shuffle=True)
    r = (len(x)-len(x)*0.95)
    X_emb = X_emb.append(X_aux.iloc[0:int(r)])
    y_emb = y_emb.append(y_aux)
    return (X_emb, y_emb)

def cria(x,y):
    X_aux, X_emb, y_aux, y_emb = train_test_split(x, y, test_size=0.95 ,shuffle=False)
    r = (len(x)-len(x)*0.95)
    X_emb = X_emb.append(X_aux.iloc[0:int(r)])
    y_emb = y_emb.append(y_aux)
    return (X_emb, y_emb)


In [13]:
X_total, y_total = cria(df, df.Sick)

In [14]:
y_total

52    0
53    0
54    0
55    0
56    0
     ..
47    1
48    1
49    1
50    1
51    1
Name: Sick, Length: 1040, dtype: int64

In [ ]:
#from sklearn.decomposition import PCA

#pca = PCA(n_components=28)
#principalComponents = pca.fit_transform(X_total)
#principalDf = pd.DataFrame(data = principalComponents
             , columns = ['Jitter_local','Jitter_local_absolute','Jitter_rap','Jitter_ppq5',
                          'Jitter_ddp','Shimmer_local','Shimmer_localdB','Shimmer_apq3','Shimmer_apq5',
                          'Shimmer_apq11','Shimmer_dda','AC','NTH','HTN','Median_pitch','Mean_pitch',
                          'Standard_deviation','Minimum_pitch','Maximum_pitch','Num_pulses','Num_periods',
                          'Mean_periods','Standard_deviation_period','Fraction_locally_unvoiced_frames',
                          'Num_voice_breaks','Degree_voice_breaks','Exame','Sick'])

In [ ]:
#principalDf

In [ ]:
#finalDf = pd.concat([principalDf, df['Sick']], axis = 1)

In [ ]:
#finalDf

In [15]:
#Teste = grupo 1

In [16]:

X_test, X_train, y_test, y_train = train_test_split(df, df.Sick, test_size=0.75 ,shuffle=False)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(780, 28) (780,)
(260, 28) (260,)


In [17]:
X_test

Jitter_local  Jitter_local_absolute  Jitter_rap  Jitter_ppq5  Jitter_ddp  \
0          471.00               0.000034      186.00         0.23       558.0   
1         4319.00               0.000317     2774.00      1708.00      8322.0   
2         1543.00               0.000103     1004.00       648.00      3012.0   
3         2864.00               0.000212     1108.00      1147.00      3324.0   
4         3878.00               0.000301     1795.00      1675.00      5386.0   
..            ...                    ...         ...          ...         ...   
255       5189.00               0.000396     2433.00      2904.00      7298.0   
256       6572.00               0.000713     2255.00      1772.00      6764.0   
257       1076.00               0.000105        0.48         0.67      1441.0   
258          4.49               0.000459     2449.00      1599.00      7346.0   
259       1546.00               0.000161      751.00       853.00      2254.0   

     Shimmer_local  Shimmer_localdB  Shimmer_apq3  Shimmer_apq5  \
0           2793.0             0.26        1183.0          1.52   
1          13924.0          1195.00        8558.0       6036.00   
2          17447.0          1694.00       11171.0       6851.00   
3           7692.0          1062.00        2555.0       4647.00   
4          11574.0          1212.00        3994.0          5.69   
..             ...              ...           ...           ...   
255        19593.0          1789.00       10638.0      12213.00   
256        11705.0          1044.00           3.7          6.06   
257        11905.0          1044.00        5752.0       8969.00   
258        18809.0          1766.00        7616.0      13887.00   
259        19126.0          1829.00       10391.0      11834.00   

     Shimmer_apq11  ...  Maximum_pitch  Num_pulses  Num_periods  Mean_periods  \
0          2576.00  ...         145.84         176          175      0.007179   
1          8585.00  ...      165029.00         258          256      0.007343   
2          9395.00  ...      158612.00         426          425      0.006700   
3         11916.00  ...      163011.00          74           70      0.007405   
4         13043.00  ...      162874.00          71           68      0.007766   
..             ...  ...            ...         ...          ...           ...   
255        6105.00  ...      425219.00          48           45      0.007640   
256       15491.00  ...      111943.00          18           16      0.010846   
257          11.49  ...      110272.00          26           25      0.009765   
258       14122.00  ...      117367.00          32           30      0.010220   
259       22685.00  ...      106842.00          28           27      0.010428   

     Standard_deviation_period   Fraction_locally_unvoiced_frames  \
0                      0.000130                               0.0   
1                      0.000312                            2913.0   
2                      0.000108                             351.0   
3                      0.000660                           18056.0   
4                      0.001045                           25333.0   
..                          ...                               ...   
255                    0.003399                           33962.0   
256                    0.001844                           59459.0   
257                    0.000489                              10.0   
258                    0.000849                           27273.0   
259                    0.000522                              20.0   

     Num_voice_breaks  Degree_voice_breaks  Exame  Sick  
0                   0                 0.00      1     0  
1                   1              7038.00      2     0  
2                   0                 0.00      3     0  
3                   2              6777.00      4     0  
4                   2                11.75      5     0  
..                ...                  ...    ...   ...  
255                

In [18]:
#-------------------------------------

In [19]:
#Teste = grupo 2

In [20]:

X_test2, X_train2, y_test2, y_train2 = train_test_split(df, df.Sick, test_size=0.5 ,shuffle=False)

print(X_train2.shape, y_train2.shape)
print(X_test2.shape, y_test2.shape)

(520, 28) (520,)
(520, 28) (520,)


In [21]:
X_aux, X_test2, y_aux, y_test2 = train_test_split(X_test2, y_test2, test_size=0.5 ,shuffle=False)
print(X_test2.shape, y_test2.shape)

(260, 28) (260,)


In [22]:
X_train2 = X_aux.append(X_train2)
y_train2 = y_aux.append(y_train2)

In [23]:
X_test2

Jitter_local  Jitter_local_absolute  Jitter_rap  Jitter_ppq5  Jitter_ddp  \
260         553.0               0.000052      212.00       215.00       637.0   
261         806.0               0.000075      149.00       259.00       448.0   
262         482.0               0.000040      142.00       151.00       426.0   
263        2036.0               0.000177      828.00      1229.00      2485.0   
264        2574.0               0.000230     1089.00      1401.00      3268.0   
..            ...                    ...         ...          ...         ...   
515        2889.0               0.000238        1.22         1.52      3659.0   
516        2283.0               0.000161     1175.00      1265.00      3526.0   
517        2598.0               0.000298     1021.00       859.00      3063.0   
518        2633.0               0.000299        0.99      1072.00      2971.0   
519        4169.0               0.000231     2075.00      1988.00      6225.0   

     Shimmer_local  Shimmer_localdB  Shimmer_apq3  Shimmer_apq5  \
260        4055.00             0.40        1787.0       2611.00   
261        5459.00           637.00        1802.0          3.21   
262           5.36           506.00        1731.0       2838.00   
263        8123.00           906.00        3999.0       5369.00   
264       11389.00          1144.00        5026.0       7266.00   
..             ...              ...           ...           ...   
515       15262.00             1.48        7064.0       8352.00   
516       18213.00          1506.00        9236.0      11632.00   
517       11073.00           997.00        6086.0       5516.00   
518          11.53          1015.00        4457.0       7028.00   
519       17203.00          1795.00        5753.0      11491.00   

     Shimmer_apq11  ...  Maximum_pitch  Num_pulses  Num_periods  Mean_periods  \
260        4197.00  ...      120752.00         258          257      0.009348   
261        6291.00  ...      119053.00          95           94      0.009335   
262        6808.00  ...      134813.00         167          165      0.008295   
263        7726.00  ...      123134.00          43           42      0.008682   
264        8849.00  ...      125471.00          55           53      0.008917   
..             ...  ...            ...         ...          ...           ...   
515       21693.00  ...      489918.00          38           34      0.008230   
516       12553.00  ...      499912.00          58           45      0.007057   
517        7674.00  ...      106678.00          25           24      0.011483   
518       13754.00  ...      101959.00          32           30      0.011360   
519          14.84  ...         490.67          67           53      0.005547   

     Standard_deviation_period   Fraction_locally_unvoiced_frames  \
260                    0.000544                               0.0   
261                    0.000879                            2222.0   
262                    0.000629                             725.0   
263                    0.000546                           26531.0   
264                    0.000763                           26562.0   
..                          ...                               ...   
515                    0.004264                           41379.0   
516                    0.004475                           38889.0   
517                    0.000895                           34091.0   
518                    0.001239                           29091.0   
519                    0.004217                           54023.0   

     Num_voice_breaks  Degree_voice_breaks  Exame  Sick  
260                 0                  0.0      1     0  
261                 0                  0.0      2     0  
262                 1               1436.0      3     0  
263                 0                  0.0      4     0  
264                 1              25493.0      5     0  
..                ...                  ...    ...   ...  
515                

In [24]:
#-------------------------------------

In [25]:
#Teste = grupo 3

In [26]:

X_train3, X_test3, y_train3, y_test3 = train_test_split(df, df.Sick, test_size=0.5 ,shuffle=False)

print(X_train3.shape, y_train3.shape)
print(X_test3.shape, y_test3.shape)

(520, 28) (520,)
(520, 28) (520,)


In [27]:
X_test3, X_aux, y_test3, y_aux = train_test_split(X_test3, y_test3, test_size=0.5 ,shuffle=False)

print(X_test3.shape, y_test3.shape)
print(X_aux.shape, y_aux.shape)

(260, 28) (260,)
(260, 28) (260,)


In [28]:
X_train3 = X_train3.append(X_aux)
y_train3 = y_train3.append(y_aux)

In [29]:
X_test3

Jitter_local  Jitter_local_absolute  Jitter_rap  Jitter_ppq5  Jitter_ddp  \
520         918.0               0.000067       408.0        532.0      1224.0   
521         384.0               0.000027       171.0        179.0       512.0   
522         343.0               0.000023       131.0        164.0       394.0   
523        3721.0               0.000291      1557.0       1886.0      4672.0   
524        2394.0               0.000201       924.0        652.0      2773.0   
..            ...                    ...         ...          ...         ...   
775        3051.0               0.000142      1648.0       1889.0      4944.0   
776        4973.0               0.000242      2115.0       2297.0      6344.0   
777        3135.0               0.000145      1651.0       1781.0      4952.0   
778        3446.0               0.000162      1674.0       2088.0      5022.0   
779        1202.0               0.000057       482.0        703.0      1446.0   

     Shimmer_local  Shimmer_localdB  Shimmer_apq3  Shimmer_apq5  \
520         5093.0           477.00       2497.00        3079.0   
521         3351.0             0.32          1.80        1838.0   
522         3041.0           345.00       1247.00        1698.0   
523         5954.0           629.00       2267.00        3621.0   
524         7947.0           764.00       3031.00        4957.0   
..             ...              ...           ...           ...   
775        10262.0           966.00          3.21        4723.0   
776        15507.0          1536.00       5549.00        7243.0   
777         9268.0          1002.00       3085.00        4427.0   
778        14816.0          1246.00       5054.00        7278.0   
779         9507.0           865.00       2209.00        3841.0   

     Shimmer_apq11  ...  Maximum_pitch  Num_pulses  Num_periods  Mean_periods  \
520        4575.00  ...       145219.0         233          231      0.007287   
521        2512.00  ...       151512.0         179          178      0.006949   
522        2601.00  ...       156943.0         170          169      0.006683   
523        3709.00  ...       140899.0          40           39      0.007824   
524        8714.00  ...       129269.0          32           30      0.008387   
..             ...  ...            ...         ...          ...           ...   
775       10221.00  ...       229673.0         104          103      0.004660   
776       14376.00  ...       239838.0         111          105      0.004867   
777       12336.00  ...       239661.0          98           96      0.004633   
778          13.35  ...       233876.0          95           94      0.004709   
779        9063.00  ...       219085.0          83           82      0.004768   

     Standard_deviation_period   Fraction_locally_unvoiced_frames  \
520                    0.000461                            1765.0   
521                    0.000210                            1587.0   
522                    0.000228                           12879.0   
523                    0.000727                            9375.0   
524                    0.000477                           26829.0   
..                          ...                               ...   
775                    0.000334                           21053.0   
776                    0.000867                           23611.0   
777                    0.000322                               0.0   
778                    0.000368                            3704.0   
779                    0.000258                           14286.0   

     Num_voice_breaks  Degree_voice_breaks  Exame  Sick  
520                 0                  0.0      1     0  
521                 0                  0.0      2     0  
522                 0                  0.0      3     0  
523                 0                  0.0      4     0  
524                 1              30704.0      5     0  
..                ...                  ...    ...   ...  
775                

In [30]:
#-------------------------------------

In [31]:
#Teste = grupo 4

In [32]:

X_train4, X_test4, y_train4, y_test4 = train_test_split(df, df.Sick, test_size=0.25 ,shuffle=False)

print(X_train4.shape, y_train4.shape)
print(X_test4.shape, y_test4.shape)

(780, 28) (780,)
(260, 28) (260,)


In [33]:
X_test4

Jitter_local  Jitter_local_absolute  Jitter_rap  Jitter_ppq5  \
780          826.0               0.000057       244.0        314.0   
781          636.0               0.000045       259.0        306.0   
782         1251.0               0.000074       542.0        474.0   
783         1726.0               0.000138       925.0        756.0   
784         3322.0               0.000266      1813.0       1574.0   
...            ...                    ...         ...          ...   
1035        1909.0               0.000103       786.0        577.0   
1036        1992.0               0.000118       911.0        866.0   
1037        1845.0               0.000100      1073.0       1096.0   
1038        2345.0               0.000127       937.0       1173.0   
1039        3515.0               0.000201      1618.0       2088.0   

      Jitter_ddp  Shimmer_local  Shimmer_localdB  Shimmer_apq3  Shimmer_apq5  \
780       733.00        6756.00             0.71        2401.0          3.13   
781       777.00        5871.00           574.00        2827.0       3202.00   
782      1627.00        4439.00           579.00        1482.0       2228.00   
783      2774.00        9162.00           907.00        4037.0       5087.00   
784         5.44          10.73          1069.00        3848.0       4321.00   
...          ...            ...              ...           ...           ...   
1035     2357.00        8885.00           833.00        4256.0          5.46   
1036     2733.00       19904.00          1713.00       11212.0      10396.00   
1037     3219.00       11451.00          1052.00        5815.0       6652.00   
1038     2811.00       12952.00          1167.00        5976.0       8343.00   
1039     4855.00       10881.00          1013.00        5124.0       7445.00   

      Shimmer_apq11  ...  Maximum_pitch  Num_pulses  Num_periods  \
780     8069.000000  ...      470707.00         158          155   
781     4674.000000  ...      159183.00         123          121   
782        4.060000  ...         200.04         111          106   
783        9.830000  ...      130653.00          38           37   
784    10846.000000  ...      135935.00          38           36   
...             ...  ...            ...         ...          ...   
1035       5.890000  ...      209393.00          40           38   
1036      11.297792  ...      178444.00          18           16   
1037   10227.000000  ...      207612.00          59           58   
1038   11774.000000  ...      227605.00          68           66   
1039      10.020000  ...      201873.00          74           72   

      Mean_periods  Standard_deviation_period   \
780       0.006936                    0.001340   
781       0.007076                    0.000313   
782       0.005889                    0.001184   
783       0.007992                    0.000238   
784       0.008003                    0.000603   
...            ...                         ...   
1035      0.005370                    0.000366   
1036      0.005910                    0.000158   
1037      0.005399                    0.000238   
1038      0.005418                    0.000712   
1039      0.005730                    0.000510   

      Fraction_locally_unvoiced_frames  Num_voice_breaks  Degree_voice_breaks  \
780                           17557.00                 1               3342.0   
781                              11.00                 0                  0.0   
782                           26136.00                 1               5343.0   
783                              24.39                 0                  0.0   
784                           39216.00                 1              28019.0   
...                                ...               ...                  ...   
1035                          62295.00                 1              35053.0   
1036                          71111.00                 1              54629.0   
1037                          19512.00                 0 

In [34]:
#-------------------------------------

In [35]:
#embaralhando (não embaralhar)
#X_train, y_train = embaralha(X_train, y_train)
#X_test, y_test = embaralha(X_test, y_test)

#X_train2, y_train2 = embaralha(X_train2, y_train2)
#X_test2, y_test2 = embaralha(X_test2, y_test2)

#X_train3, y_train3 = embaralha(X_train3, y_train3)
#X_test3, y_test3 = embaralha(X_test3, y_test3)

#X_train4, y_train4 = embaralha(X_train4, y_train4)
#X_test4, y_test4 = embaralha(X_test4, y_test4)


In [36]:
#Normalizando os dados

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

X_train2 = sc.fit_transform(X_train2)
X_test2 = sc.fit_transform(X_test2)

X_train3 = sc.fit_transform(X_train3)
X_test3 = sc.fit_transform(X_test3)

X_train4 = sc.fit_transform(X_train4)
X_test4 = sc.fit_transform(X_test4)


In [37]:
X_total = sc.fit_transform(X_total)

In [38]:
#####################################################
#Aplicação SVM Linear
#####################################################

In [39]:
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [40]:
## Aplicação de Hiperparâmetros GRUPO 1
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmLin = GridSearchCV(Grid(kernel='linear'), param_grid, cv=5)
modelo_SvmLin.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [41]:
modelo_SvmLin.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [42]:
#SVM polinomial aplicado

modelo_SvmLin = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmLin.fit(X_train, y_train)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [43]:
y_pred_modelLin = modelo_SvmLin.predict(X_test)
y_pred_modelLin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
## Aplicação de Hiperparâmetros GRUPO 2
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmLin2 = GridSearchCV(Grid(kernel='linear'), param_grid, cv=5)
modelo_SvmLin2.fit(X_train2, y_train2)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [45]:
modelo_SvmLin2.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
#SVM polinomial aplicado

modelo_SvmLin2 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmLin2.fit(X_train2, y_train2)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [47]:
y_pred_Lin2 = modelo_SvmLin2.predict(X_test2)

In [48]:
y_pred_modelLin = np.append(y_pred_modelLin, y_pred_Lin2)
y_pred_modelLin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [49]:
## Aplicação de Hiperparâmetros GRUPO 3
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmLin3 = GridSearchCV(Grid(kernel='linear'), param_grid, cv=5)
modelo_SvmLin3.fit(X_train3, y_train3)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [50]:
modelo_SvmLin3.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [51]:
#SVM polinomial aplicado

modelo_SvmLin3 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmLin3.fit(X_train3, y_train3)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [52]:
y_pred_Lin3 = modelo_SvmLin3.predict(X_test3)

In [53]:
y_pred_modelLin = np.append(y_pred_modelLin, y_pred_Lin3)
y_pred_modelLin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [54]:
## Aplicação de Hiperparâmetros GRUPO 4
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmLin4 = GridSearchCV(Grid(kernel='linear'), param_grid, cv=5)
modelo_SvmLin4.fit(X_train4, y_train4)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [55]:
modelo_SvmLin4.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [56]:
#SVM polinomial aplicado

modelo_SvmLin4 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmLin4.fit(X_train4, y_train4)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [57]:
y_pred_Lin4 = modelo_SvmLin4.predict(X_test4)

In [58]:
y_pred_modelLin = np.append(y_pred_modelLin, y_pred_Lin4)
y_pred_modelLin

array([0, 0, 0, ..., 1, 1, 1])

In [59]:
###########
y_pred_modelLin.shape

(1040,)

In [60]:
# Acurácia
print("Acurácia com K-fold SVM POlinomial:", accuracy_score(y_total, y_pred_modelLin))

Acurácia com K-fold SVM POlinomial: 1.0


In [61]:
print(confusion_matrix(y_total, y_pred_modelLin))
print(classification_report(y_total, y_pred_modelLin))
print("Acurácia Polinomial:", accuracy_score(y_total, y_pred_modelLin))

[[520   0]
 [  0 520]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       520
           1       1.00      1.00      1.00       520

    accuracy                           1.00      1040
   macro avg       1.00      1.00      1.00      1040
weighted avg       1.00      1.00      1.00      1040

Acurácia Polinomial: 1.0


In [62]:
#####################################################
#Aplicação SVM Polinomial
#####################################################

In [63]:
## Aplicação de Hiperparâmetros GRUPO 1
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmPoly = GridSearchCV(Grid(kernel='poly'), param_grid, cv=5)
modelo_SvmPoly.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='poly', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [64]:
modelo_SvmPoly.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [65]:
#SVM polinomial aplicado

modelo_SvmPoly = svm.SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmPoly.fit(X_train, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [66]:
y_pred_modelPoly= modelo_SvmPoly.predict(X_test)
y_pred_modelPoly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
#----------------------------------------

In [68]:
## Aplicação de Hiperparâmetros GRUPO 2
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmPoly2 = GridSearchCV(Grid(kernel='poly'), param_grid, cv=5)
modelo_SvmPoly2.fit(X_train2, y_train2)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='poly', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [69]:
modelo_SvmPoly2.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [70]:
#SVM polinomial aplicado

modelo_SvmPoly2 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmPoly2.fit(X_train2, y_train2)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [71]:
y_pred2 = modelo_SvmPoly2.predict(X_test2)

In [72]:
y_pred_modelPoly = np.append(y_pred_modelPoly, y_pred2)
y_pred_modelPoly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [73]:
#---------------------------------------------

In [74]:
## Aplicação de Hiperparâmetros GRUPO 3
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmPoly3 = GridSearchCV(Grid(kernel='poly'), param_grid, cv=5)
modelo_SvmPoly3.fit(X_train3, y_train3)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='poly', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [75]:
modelo_SvmPoly3.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [76]:
#SVM polinomial aplicado

modelo_SvmPoly3 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmPoly3.fit(X_train3, y_train3)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
y_pred3 = modelo_SvmPoly3.predict(X_test3)

In [78]:
y_pred_modelPoly = np.append(y_pred_modelPoly, y_pred3)
y_pred_modelPoly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [79]:
#---------------------------------------------

In [80]:
## Aplicação de Hiperparâmetros GRUPO 4
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmPoly4 = GridSearchCV(Grid(kernel='poly'), param_grid, cv=5)
modelo_SvmPoly4.fit(X_train4, y_train4)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='poly', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [81]:
modelo_SvmPoly4.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [82]:
#SVM polinomial aplicado

modelo_SvmPoly4 = svm.SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

modelo_SvmPoly4.fit(X_train4, y_train4)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [83]:
y_pred4 = modelo_SvmPoly4.predict(X_test4)

In [84]:
y_pred_modelPoly = np.append(y_pred_modelPoly, y_pred4)
print(len(y_pred_modelPoly))

1040


In [85]:
#------------------------------------------

In [86]:
y_pred_modelPoly.shape

(1040,)

In [87]:
# Acurácia
print("Acurácia com K-fold SVM POlinomial:", accuracy_score(y_total, y_pred_modelPoly))

Acurácia com K-fold SVM POlinomial: 1.0


In [88]:
print(confusion_matrix(y_total, y_pred_modelPoly))
print(classification_report(y_total, y_pred_modelPoly))
print("Acurácia Polinomial:", accuracy_score(y_total, y_pred_modelPoly))

[[520   0]
 [  0 520]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       520
           1       1.00      1.00      1.00       520

    accuracy                           1.00      1040
   macro avg       1.00      1.00      1.00      1040
weighted avg       1.00      1.00      1.00      1040

Acurácia Polinomial: 1.0


In [89]:
#############################################

In [90]:
## MODELO SVM com Kernel RBF

In [91]:
## Aplicação de Hiperparâmetros GRUPO 1
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmRBF = GridSearchCV(Grid(kernel='rbf'), param_grid, cv=5)
modelo_SvmRBF.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [92]:
modelo_SvmRBF.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [93]:
#Gerando o modelo com kernel RBF

modelo_SvmRBF = svm.SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) 

modelo_SvmRBF.fit(X_train, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [94]:
y_pred_rbf = modelo_SvmRBF.predict(X_test)

In [95]:
#-----------------------------------------

In [96]:
## Aplicação de Hiperparâmetros GRUPO 2
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmRBF2 = GridSearchCV(Grid(kernel='rbf'), param_grid, cv=5)
modelo_SvmRBF2.fit(X_train2, y_train2)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [97]:
modelo_SvmRBF2.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [98]:
#Gerando o modelo com kernel RBF

modelo_SvmRBF2 = svm.SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) 

modelo_SvmRBF2.fit(X_train2, y_train2)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [99]:
y_pred_rbf2 = modelo_SvmRBF2.predict(X_test2)

In [100]:
y_pred_rbf = np.append(y_pred_rbf, y_pred_rbf2)
y_pred_rbf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [101]:
#----------------------------------------------------------

In [102]:
## Aplicação de Hiperparâmetros GRUPO 3
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmRBF3 = GridSearchCV(Grid(kernel='rbf'), param_grid, cv=5)
modelo_SvmRBF3.fit(X_train3, y_train3)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [103]:
modelo_SvmRBF3.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [104]:
#Gerando o modelo com kernel RBF

modelo_SvmRBF3 = svm.SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) 

modelo_SvmRBF3.fit(X_train3, y_train3)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [105]:
y_pred_rbf3 = modelo_SvmRBF3.predict(X_test3)

In [106]:
y_pred_rbf = np.append(y_pred_rbf, y_pred_rbf3)
y_pred_rbf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [107]:
#--------------------------------------------

In [108]:
## Aplicação de Hiperparâmetros GRUPO 4
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]}

Grid = svm.SVC 
modelo_SvmRBF4 = GridSearchCV(Grid(kernel='rbf'), param_grid, cv=5)
modelo_SvmRBF4.fit(X_train4, y_train4)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [109]:
modelo_SvmRBF4.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [110]:
#Gerando o modelo com kernel RBF

modelo_SvmRBF4 = svm.SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) 

modelo_SvmRBF4.fit(X_train4, y_train4)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [111]:
y_pred_rbf4 = modelo_SvmRBF4.predict(X_test4)

In [112]:
y_pred_rbf = np.append(y_pred_rbf, y_pred_rbf4)
y_pred_rbf

array([0, 0, 0, ..., 1, 1, 1])

In [113]:
#------------------------------------------------

In [114]:
y_pred_rbf.shape

(1040,)

In [115]:
# Acurácia SVM RBF
print("Acurácia K-fold SVM RBF", accuracy_score(y_total, y_pred_rbf))

Acurácia K-fold SVM RBF 1.0


In [116]:
# Avaliação do modelo

print(confusion_matrix(y_total,y_pred_rbf))
print(classification_report(y_total,y_pred_rbf))  
print("Acurácia RBF:", accuracy_score(y_total, y_pred_rbf))

[[520   0]
 [  0 520]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       520
           1       1.00      1.00      1.00       520

    accuracy                           1.00      1040
   macro avg       1.00      1.00      1.00      1040
weighted avg       1.00      1.00      1.00      1040

Acurácia RBF: 1.0


In [117]:
#############################################
#Aplicação do KNN
from sklearn.neighbors import KNeighborsClassifier

In [118]:
## Aplicação de Hiperparâmetros GRUPO 1
from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

k_range = list(range(1, 31))

param_grid = dict(n_neighbors=k_range)

model_KNN = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
model_KNN.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [119]:
model_KNN.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [120]:
model_KNN = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')
model_KNN.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [121]:
y_pred_knn = model_KNN.predict(X_test)

In [122]:
#------------------------------------------

In [123]:
## Aplicação de Hiperparâmetros GRUPO 2
from sklearn.model_selection import GridSearchCV

k_range = list(range(1, 31))

param_grid = dict(n_neighbors=k_range)

model_KNN2 = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
model_KNN2.fit(X_train2, y_train2)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [124]:
model_KNN2.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=26, p=2,
                     weights='uniform')

In [125]:
model_KNN2 = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=26, p=2,
                     weights='uniform')
model_KNN2.fit(X_train2, y_train2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=26, p=2,
                     weights='uniform')

In [126]:
y_pred_knn2 = model_KNN2.predict(X_test2)

In [127]:
y_pred_knn = np.append(y_pred_knn, y_pred_knn2)
y_pred_knn

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [128]:
#--------------------------------------------

In [129]:
## Aplicação de Hiperparâmetros GRUPO 3
from sklearn.model_selection import GridSearchCV

k_range = list(range(1, 31))

param_grid = dict(n_neighbors=k_range)

model_KNN3 = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
model_KNN3.fit(X_train3, y_train3)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [130]:
model_KNN3.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=19, p=2,
                     weights='uniform')

In [131]:
model_KNN3 = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=19, p=2,
                     weights='uniform')
model_KNN3.fit(X_train3, y_train3)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=19, p=2,
                     weights='uniform')

In [132]:
y_pred_knn3 = model_KNN3.predict(X_test3)

In [133]:
y_pred_knn = np.append(y_pred_knn, y_pred_knn3)
y_pred_knn

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [134]:
#-------------------------------------------

In [135]:
## Aplicação de Hiperparâmetros GRUPO 4
from sklearn.model_selection import GridSearchCV

k_range = list(range(1, 31))

param_grid = dict(n_neighbors=k_range)

model_KNN4 = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
model_KNN4.fit(X_train4, y_train4)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [136]:
model_KNN4.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=24, p=2,
                     weights='uniform')

In [137]:
model_KNN4 = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=24, p=2,
                     weights='uniform')
model_KNN4.fit(X_train4, y_train4)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=24, p=2,
                     weights='uniform')

In [138]:
y_pred_knn4 = model_KNN4.predict(X_test4)

In [139]:
y_pred_knn = np.append(y_pred_knn, y_pred_knn4)
y_pred_knn

array([0, 1, 0, ..., 1, 1, 1])

In [140]:
#--------------------------------------------------

In [141]:
y_pred_knn.shape

(1040,)

In [142]:
# Acurácia SVM RBF
print("Acurácia K-fold KNN", accuracy_score(y_total, y_pred_knn))

Acurácia K-fold KNN 0.926923076923077


In [143]:
print(confusion_matrix(y_total,y_pred_knn))
print(classification_report(y_total,y_pred_knn))  
print("Acurácia RBF:", accuracy_score(y_total, y_pred_knn))

[[487  33]
 [ 43 477]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       520
           1       0.94      0.92      0.93       520

    accuracy                           0.93      1040
   macro avg       0.93      0.93      0.93      1040
weighted avg       0.93      0.93      0.93      1040

Acurácia RBF: 0.926923076923077


In [144]:
###################################################

In [145]:
###################################################

In [146]:
#Agora o teste será realizado em um dataset com 6 exames de 28 pacientes com Parkinson, todos com a doença
# Serão 168 instancias (6 exames x 28 pacientes) embaralhadas

In [147]:
PD = pd.read_csv('test_data.csv')
del PD['paciente']

In [148]:
y_final = PD.Sick
X_final = PD

In [ ]:
X_final, y_final = embaralha(X_final, y_final)

In [149]:
X_final = sc.fit_transform(X_final)
print(X_final.shape, y_final.shape)

(168, 28) (168,)


In [150]:
#GRUPO 1

for modelo in (modelo_SvmLin, modelo_SvmPoly, modelo_SvmRBF, model_KNN):
    name = modelo
    y_pred_name = modelo.predict(X_final)
    print("Acurácia", modelo.__class__.__name__,  accuracy_score(y_final, y_pred_name))
    print(classification_report(y_final,y_pred_name))

Acurácia SVC 0.5059523809523809
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.51      0.67       168

    accuracy                           0.51       168
   macro avg       0.50      0.25      0.34       168
weighted avg       1.00      0.51      0.67       168

Acurácia SVC 0.6130952380952381
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.61      0.76       168

    accuracy                           0.61       168
   macro avg       0.50      0.31      0.38       168
weighted avg       1.00      0.61      0.76       168

Acurácia SVC 0.42857142857142855
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.43      0.60       168

    accuracy                           0.43       168
   macro avg       0.50      0.

/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/

In [152]:
#GRUPO 2

for modelo in (modelo_SvmLin2, modelo_SvmPoly2, modelo_SvmRBF2, model_KNN2):
    name = modelo
    y_pred_name = modelo.predict(X_final)
    print("Acurácia", modelo.__class__.__name__,  accuracy_score(y_final, y_pred_name))
    print(classification_report(y_final,y_pred_name))

Acurácia SVC 0.44047619047619047
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.44      0.61       168

    accuracy                           0.44       168
   macro avg       0.50      0.22      0.31       168
weighted avg       1.00      0.44      0.61       168

Acurácia SVC 0.49404761904761907
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.49      0.66       168

    accuracy                           0.49       168
   macro avg       0.50      0.25      0.33       168
weighted avg       1.00      0.49      0.66       168

Acurácia SVC 0.47023809523809523
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.47      0.64       168

    accuracy                           0.47       168
   macro avg       0.50      

/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/

In [162]:
#GRUPO 3

for modelo in (modelo_SvmLin3, modelo_SvmPoly3, modelo_SvmRBF3, model_KNN3):
    modelo.fit(X_train3, y_train3)
    name = modelo
    y_pred_name = modelo.predict(X_final)
    print("Acurácia", modelo.__class__.__name__,  accuracy_score(y_final, y_pred_name))
    print(classification_report(y_final,y_pred_name))

Acurácia SVC 0.5595238095238095
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.56      0.72       168

    accuracy                           0.56       168
   macro avg       0.50      0.28      0.36       168
weighted avg       1.00      0.56      0.72       168

Acurácia SVC 0.20238095238095238
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.20      0.34       168

    accuracy                           0.20       168
   macro avg       0.50      0.10      0.17       168
weighted avg       1.00      0.20      0.34       168

Acurácia SVC 0.4107142857142857
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.41      0.58       168

    accuracy                           0.41       168
   macro avg       0.50      0.

/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/

In [155]:
#GRUPO 4

for modelo in (modelo_SvmLin4, modelo_SvmPoly4, modelo_SvmRBF4, model_KNN4):
    name = modelo
    y_pred_name = modelo.predict(X_final)
    print("Acurácia", modelo.__class__.__name__,  accuracy_score(y_final, y_pred_name))
    print(classification_report(y_final,y_pred_name))

Acurácia SVC 0.5059523809523809
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.51      0.67       168

    accuracy                           0.51       168
   macro avg       0.50      0.25      0.34       168
weighted avg       1.00      0.51      0.67       168

Acurácia SVC 0.5595238095238095
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.56      0.72       168

    accuracy                           0.56       168
   macro avg       0.50      0.28      0.36       168
weighted avg       1.00      0.56      0.72       168

Acurácia SVC 0.5595238095238095
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.56      0.72       168

    accuracy                           0.56       168
   macro avg       0.50      0.2

/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/

In [ ]:
#################################

In [159]:
#GRUPO TOTAL

for modelo in (modelo_SvmLin, modelo_SvmPoly, modelo_SvmRBF, model_KNN):
    modelo.fit(X_total,y_total)
    name = modelo
    y_pred_name = modelo.predict(X_final)
    print("Acurácia", modelo.__class__.__name__,  accuracy_score(y_final, y_pred_name))
    print(classification_report(y_final,y_pred_name))

Acurácia SVC 0.4642857142857143
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.46      0.63       168

    accuracy                           0.46       168
   macro avg       0.50      0.23      0.32       168
weighted avg       1.00      0.46      0.63       168

Acurácia SVC 0.43452380952380953
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.43      0.61       168

    accuracy                           0.43       168
   macro avg       0.50      0.22      0.30       168
weighted avg       1.00      0.43      0.61       168

Acurácia SVC 0.4523809523809524
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.45      0.62       168

    accuracy                           0.45       168
   macro avg       0.50      0.

/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mariohn/anaconda3/lib/python3.7/site-packages/